In [2]:
#imports
import numpy as np
import pandas as pd # trifecta
import matplotlib.pyplot as plt

import h5py #to read in h5 file 
import random #to shuffle indices

from numpy import pi

import sys
import os 

sys.path.append('/home/ishan/honors_thesis')
from rnn_utils import *

np.random.seed(0) #seed for reproducability

In [ ]:
dataFolder = '/home/ishan/princeton_data/preds/'
file = os.listdir(dataFolder)
#for file in os.listdir(dataFolder):
    #pos = h5py.File(dataFolder + file)['positions_pred']
    ja = getJointAngles(pos[1000:])
    ja = ja.reshape((ja.shape[0], ja.shape[2]))
    with h5py.File('/home/ishan/honors_thesis/joint_angles/ja_{}'.format(file), 'w') as h5f:
        h5f.create_dataset('joint_angles', data = ja)

In [12]:
jaFolder = '/home/ishan/honors_thesis/joint_angles/old/'

X_train, Y_train, X_val, Y_val, indices_used = create_dataset(jaFolder=jaFolder, num_samples = 1500, split_proportion=0.667, Y_shape = ('N', 'lag', 'num_feats'))

In [4]:
with h5py.File('Xtrain.h5', 'w') as h5f:
    h5f.create_dataset('joint_angles', data=X_train)
with h5py.File('Ytrain.h5', 'w') as h5f:
    h5f.create_dataset('joint_angles', data=Y_train)
with h5py.File('Xval.h5', 'w') as h5f:
    h5f.create_dataset('joint_angles', data=X_val)
with h5py.File('Yval.h5', 'w') as h5f:
    h5f.create_dataset('joint_angles', data=Y_val)

In [13]:
#Checks - various checks, but it works... :) 
X_train = h5py.File('validation_set/Xtrain.h5')['joint_angles']
Y_train = h5py.File('validation_set/Ytrain.h5')['joint_angles']
file = os.listdir(jaFolder)[0]
ja = h5py.File(jaFolder + file)['joint_angles']

row = 1
tmp = 8 
[X_train[j][i+1] == Y_train[j][i] for i in range(9) for j in range(10)]

[array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]),
 array([ True,  True,  T